import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        setVisible(true);
        initComponents();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Background = new javax.swing.JPanel();
        PanelLateral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelCorreo = new javax.swing.JLabel();
        LabelContraseña = new javax.swing.JLabel();
        FieldCorreo = new javax.swing.JTextField();
        FieldContraseña = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        BotonConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));

        PanelLateral.setBackground(new java.awt.Color(227, 21, 59));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabajofinal/LogoCampito2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout PanelLateralLayout = new javax.swing.GroupLayout(PanelLateral);
        PanelLateral.setLayout(PanelLateralLayout);
        PanelLateralLayout.setHorizontalGroup(
            PanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLateralLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        PanelLateralLayout.setVerticalGroup(
            PanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(150, 150, 150))
        );

        LabelCorreo.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        LabelCorreo.setText("Escribe tu correo aquí");

        LabelContraseña.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        LabelContraseña.setText("Escribe tu contraseña aquí");

        FieldCorreo.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        FieldCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 21, 59)));
        FieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCorreoActionPerformed(evt);
            }
        });

        FieldContraseña.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        FieldContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 21, 59)));
        FieldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldContraseñaActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(233, 156, 40));
        jSeparator1.setForeground(new java.awt.Color(227, 21, 59));

        jSeparator2.setBackground(new java.awt.Color(233, 156, 40));
        jSeparator2.setForeground(new java.awt.Color(227, 21, 59));

        BotonConfirmar.setBackground(new java.awt.Color(227, 21, 59));
        BotonConfirmar.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        BotonConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        BotonConfirmar.setText("CONFIRMAR");
        BotonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LabelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(BotonConfirmar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(PanelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(LabelCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(LabelContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(BotonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void FieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        Correo=FieldCorreo.getText();
    }                                           

    private void BotonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {                                               
        //Aqui esta el codigo que se ejecuta cuando es pulsado
        FieldCorreoActionPerformed(evt);
        FieldContraseñaActionPerformed(evt);
        //Comprobamos si el text field del correo y la contraseña estan vacios
        if(Correo.equals("")&&Contraseña.equals("")){
            //Si no lo estan saldra una mensaje emergente de que se tienen que completar
            JOptionPane.showMessageDialog(null, "Error 404 correo y contaseña no encontrados");
        }
        //Comprobamos si el text field del correo esta vacio
        else if(Correo.equals("")){
            //Si no lo esta saldra una mensaje emergente de que se tienes que completar
            JOptionPane.showMessageDialog(null, "Error 404 correo no encontrado");
        }
        //Comprobamos si el text field de la contraseña esta vacio
        else if(Contraseña.equals("")){
            //Si no lo esta saldra una mensaje emergente de que se tienes que completar
            JOptionPane.showMessageDialog(null, "Error 404 contraseña no encontrada");
        }
        //Si los dos text fields contienen información
        else{
            //Cerramos el login
            dispose();
            //Abrimos la Paginap
            PaginaP p = new PaginaP();
            p.setVisible(true);
        }
    }                                              

    private void FieldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        Contraseña=FieldContraseña.getText();
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel Background;
    private javax.swing.JButton BotonConfirmar;
    private javax.swing.JPasswordField FieldContraseña;
    private javax.swing.JTextField FieldCorreo;
    private javax.swing.JLabel LabelContraseña;
    private javax.swing.JLabel LabelCorreo;
    private javax.swing.JPanel PanelLateral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration                   
    private String Correo;
    private String Contraseña;
}
