import java.awt.event.ActionEvent;
import java.sql.*;

public class PaginaEquipo extends javax.swing.JFrame {

    /**
     * Creates new form PaginaP
     */
    public PaginaEquipo() {
        //Inicializacion de los strings para mostrar la informacion de la querry
        String plantillan = "";
        String plantillaf = "";
        String plantillana = "";
        String plantillap = "";
        String plantillad = "";
        initComponents();
        //Aqui ponemos un try y catch por si la conexion no va bien
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            //A la variable conexion le indicamos "jdbc:mysql://IP:3306/Nombre de la base de datos","Nombre usuario","Contraseña"
            Connection conexion = DriverManager.getConnection("jdbc:mysql://192.168.56.2:3306/Campito","toni","1234");
            Statement s = conexion.createStatement();
            //rs es donde se guarda la ejecucion de la querry
            ResultSet rs = s.executeQuery("SELECT * FROM PLANTILLA ORDER BY Dorsal");
            
            //Bucle donde vamos guardando la información del resultado de la querry
            while(rs.next()){
                plantillan = plantillan +(rs.getString(1)+"<br>");
                LabelPlantillan.setText(plantillan);
                
                plantillaf = plantillaf +(rs.getString(2)+"<br>");
                LabelPlantillaf.setText(plantillaf);
                
                plantillana = plantillana +(rs.getString(3)+"<br>");
                LabelPlantillana.setText(plantillana);
                
                plantillap = plantillap +(rs.getString(4)+"<br>");
                LabelPlantillap.setText(plantillap);
                
                plantillad = plantillad +(rs.getInt(5)+"<br>");
                LabelPlantillad.setText(plantillad);
            }
            //Pasamos la información al label
            LabelPlantillan.setText("<html>"+plantillan+"</html>");
            
            LabelPlantillaf.setText("<html>"+plantillaf+"</html>");
            
            LabelPlantillana.setText("<html>"+plantillana+"</html>");
            
            LabelPlantillap.setText("<html>"+plantillap+"</html>");
            
            LabelPlantillad.setText("<html>"+plantillad+"</html>");
            conexion.close();
        }
        //Catch que si encuentra un error lo mostrara y dira donde ha fallado
        catch(Exception e){
            System.out.println("ERROR EN PAGINAEQUIPO");
            System.out.println(e);
        }
        setVisible(true);
        setSize(825,530);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        FondoRojo = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        BotonEquipo = new javax.swing.JButton();
        BotonCampo = new javax.swing.JButton();
        BotonEquipacion = new javax.swing.JButton();
        BotonPartidos = new javax.swing.JButton();
        BotonTienda = new javax.swing.JButton();
        LabelPlantillan = new javax.swing.JLabel();
        LabelPlantillaf = new javax.swing.JLabel();
        LabelPlantillana = new javax.swing.JLabel();
        LabelPlantillap = new javax.swing.JLabel();
        LabelPlantillad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));

        FondoRojo.setBackground(new java.awt.Color(227, 21, 59));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabajofinal/LogoCampito2.jpg"))); // NOI18N
        Logo.setText("jLabel1");

        BotonEquipo.setBackground(new java.awt.Color(227, 21, 59));
        BotonEquipo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BotonEquipo.setForeground(new java.awt.Color(255, 255, 255));
        BotonEquipo.setText("EQUIPO");
        BotonEquipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEquipoActionPerformed(evt);
            }
        });

        BotonCampo.setBackground(new java.awt.Color(227, 21, 59));
        BotonCampo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BotonCampo.setForeground(new java.awt.Color(255, 255, 255));
        BotonCampo.setText("CAMPO");
        BotonCampo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCampoActionPerformed(evt);
            }
        });

        BotonEquipacion.setBackground(new java.awt.Color(227, 21, 59));
        BotonEquipacion.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BotonEquipacion.setForeground(new java.awt.Color(255, 255, 255));
        BotonEquipacion.setText("EQUIPACIÓN");
        BotonEquipacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonEquipacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEquipacionActionPerformed(evt);
            }
        });

        BotonPartidos.setBackground(new java.awt.Color(227, 21, 59));
        BotonPartidos.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BotonPartidos.setForeground(new java.awt.Color(255, 255, 255));
        BotonPartidos.setText("PARTIDOS");
        BotonPartidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPartidosActionPerformed(evt);
            }
        });

        BotonTienda.setBackground(new java.awt.Color(227, 21, 59));
        BotonTienda.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BotonTienda.setForeground(new java.awt.Color(255, 255, 255));
        BotonTienda.setText("TIENDA");
        BotonTienda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTiendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoRojoLayout = new javax.swing.GroupLayout(FondoRojo);
        FondoRojo.setLayout(FondoRojoLayout);
        FondoRojoLayout.setHorizontalGroup(
            FondoRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoRojoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(BotonEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(BotonEquipacion, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(FondoRojoLayout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoRojoLayout.setVerticalGroup(
            FondoRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoRojoLayout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FondoRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonEquipacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        LabelPlantillan.setBackground(new java.awt.Color(255, 0, 51));
        LabelPlantillan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        LabelPlantillaf.setBackground(new java.awt.Color(255, 0, 51));
        LabelPlantillaf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        LabelPlantillana.setBackground(new java.awt.Color(255, 0, 51));
        LabelPlantillana.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        LabelPlantillap.setBackground(new java.awt.Color(255, 0, 51));
        LabelPlantillap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        LabelPlantillad.setBackground(new java.awt.Color(255, 0, 51));
        LabelPlantillad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("NOMBRE APELLIDOS");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("FECHA N");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("NACIONALIDAD");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("POSICIÓN");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("DORSAL");

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoRojo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(LabelPlantillan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50)))
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(LabelPlantillaf, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(37, 37, 37)))
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(LabelPlantillana, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(LabelPlantillap, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel4)))
                .addGap(27, 27, 27)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(LabelPlantillad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(FondoRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(4, 4, 4)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelPlantillan, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(LabelPlantillaf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelPlantillana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelPlantillap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelPlantillad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    //Aqui esta el codigo que se ejecuta cuando el boton equipo es pulsado
    private void BotonEquipoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        //Cerramos la PaginaEquipo
        dispose();
        //Abrimos la PaginaEquipo
        PaginaEquipo peq = new PaginaEquipo();
        //Con estas dimensiones
        peq.setSize(825,540);
        peq.setVisible(true);
    }                                           

    //Aqui esta el codigo que se ejecuta cuando el boton campo es pulsado
    private void BotonCampoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        //Cerramos la PaginaEquipo
        dispose();
        //Abrimos la PaginaCampo
        PaginaCampo pc = new PaginaCampo();
        //Con estas dimensiones
        pc.setSize(820,600);
        pc.setVisible(true);
    }                                          

    //Aqui esta el codigo que se ejecuta cuando el boton equipacion es pulsado
    private void BotonEquipacionActionPerformed(java.awt.event.ActionEvent evt) {                                                
        //Cerramos la PaginaEquipo
        dispose();
        //Abrimos la PaginaEquipacion
        PaginaEquipacion peqn = new PaginaEquipacion();
        //Con estas dimensiones
        peqn.setSize(820,550);
        peqn.setVisible(true);
    }                                               

    //Aqui esta el codigo que se ejecuta cuando el boton partidos es pulsado
    private void BotonPartidosActionPerformed(java.awt.event.ActionEvent evt) {                                              
        //Cerramos la PaginaEquipo
        dispose();
        //Abrimos la PaginaPartidos
        PaginaPartidos pp = new PaginaPartidos();
        pp.setVisible(true);
    }                                             

    //Aqui esta el codigo que se ejecuta cuando el boton tienda es pulsado
    private void BotonTiendaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        //Cerramos la PaginaEquipo
        dispose();
        //Abrimos la PaginaTienda
        PaginaTienda pt = new PaginaTienda();
        pt.setVisible(true);
    }                                           
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BotonCampo;
    private javax.swing.JButton BotonEquipacion;
    private javax.swing.JButton BotonEquipo;
    private javax.swing.JButton BotonPartidos;
    private javax.swing.JButton BotonTienda;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel FondoRojo;
    private javax.swing.JLabel LabelPlantillad;
    private javax.swing.JLabel LabelPlantillaf;
    private javax.swing.JLabel LabelPlantillan;
    private javax.swing.JLabel LabelPlantillana;
    private javax.swing.JLabel LabelPlantillap;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration                   
}
